In [1]:
import pandas as pd 
import numpy as np

df = pd.read_csv('Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.1+ KB

In [3]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [4]:
df.var()

Id               1887.500000
SepalLengthCm       0.685694
SepalWidthCm        0.188004
PetalLengthCm       3.113179
PetalWidthCm        0.582414
dtype: float64

In [5]:
df['SepalLengthCm'].corr(df['SepalLengthCm'])

1.0

In [6]:
df['SepalWidthCm'].corr(df['SepalWidthCm'])

1.0

In [7]:
df.corr()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Id,1.000000,0.716676,-0.397729,0.882747,0.899759
SepalLengthCm,0.716676,1.000000,-0.109369,0.871754,0.817954
SepalWidthCm,-0.397729,-0.109369,1.000000,-0.420516,-0.356544
PetalLengthCm,0.882747,0.871754,-0.420516,1.000000,0.962757
PetalWidthCm,0.899759,0.817954,-0.356544,0.962757,1.000000

In [8]:
df['PetalLengthCm'].corr(df['PetalLengthCm'])

1.0

In [9]:
df['PetalWidthCm'].corr(df['PetalWidthCm'])

1.0

In [10]:
df.corr()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Id,1.000000,0.716676,-0.397729,0.882747,0.899759
SepalLengthCm,0.716676,1.000000,-0.109369,0.871754,0.817954
SepalWidthCm,-0.397729,-0.109369,1.000000,-0.420516,-0.356544
PetalLengthCm,0.882747,0.871754,-0.420516,1.000000,0.962757
PetalWidthCm,0.899759,0.817954,-0.356544,0.962757,1.000000

In [11]:
df1 = df['PetalLengthCm']+1.5
df1

0      2.9
1      2.9
2      2.8
3      3.0
4      2.9
5      3.2
6      2.9
7      3.0
8      2.9
9      3.0
10     3.0
11     3.1
12     2.9
13     2.6
14     2.7
15     3.0
16     2.8
17     2.9
18     3.2
19     3.0
20     3.2
21     3.0
22     2.5
23     3.2
24     3.4
25     3.1
26     3.1
27     3.0
28     2.9
29     3.1
      ...
120    7.2
121    6.4
122    8.2
123    6.4
124    7.2
125    7.5
126    6.3
127    6.4
128    7.1
129    7.3
130    7.6
131    7.9
132    7.1
133    6.6
134    7.1
135    7.6
136    7.1
137    7.0
138    6.3
139    6.9
140    7.1
141    6.6
142    6.6
143    7.4
144    7.2
145    6.7
146    6.5
147    6.7
148    6.9
149    6.6
Name: PetalLengthCm, Length: 150, dtype: float64

In [12]:
df1 = df['PetalLengthCm']-1.5
df1

0     -0.1
1     -0.1
2     -0.2
3      0.0
4     -0.1
5      0.2
6     -0.1
7      0.0
8     -0.1
9      0.0
10     0.0
11     0.1
12    -0.1
13    -0.4
14    -0.3
15     0.0
16    -0.2
17    -0.1
18     0.2
19     0.0
20     0.2
21     0.0
22    -0.5
23     0.2
24     0.4
25     0.1
26     0.1
27     0.0
28    -0.1
29     0.1
      ...
120    4.2
121    3.4
122    5.2
123    3.4
124    4.2
125    4.5
126    3.3
127    3.4
128    4.1
129    4.3
130    4.6
131    4.9
132    4.1
133    3.6
134    4.1
135    4.6
136    4.1
137    4.0
138    3.3
139    3.9
140    4.1
141    3.6
142    3.6
143    4.4
144    4.2
145    3.7
146    3.5
147    3.7
148    3.9
149    3.6
Name: PetalLengthCm, Length: 150, dtype: float64

In [13]:
df2=df.copy()
df2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [14]:
df2['PetalLengthCm'].corr(df2['PetalLengthCm'])

1.0